server:
  port: 8199

path:
  upload:
    dir: /u01/afp/framework/upload
    
#Config oauth2 && JWT
spring:
  mail:    host: smtp.atwom.com.vn
    port: 25
    username: info@atwom.com.vn
    password: 123456789
  ldap:
    urls: 
      0: ldap://localhost:386
    base: dc=maxcrc,dc=com
    username: cn=Manager,dc=maxcrc,dc=com
    password: $a2minfo!@#
    enable: false
  security:
    jwt:
      secret: a2m_FrAmeWorK
      expirationMs: 28800000
      allowedOrigins: localhost:3002,afp-tool.atwom.com.vn,afp.atwom.com.vn
    oauth2:
      client:
        registration:
          google:
            client-id: 361798404348-epn398coqjqnvipps4dcjro19k8epqf4.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
            scope:            - email
            - profile
          facebook:
            client-id: 1186124622268244
            client-secret: 998ef8102ad9e5dd2237670f1824804a
            redirect-uri: "{baseUrl}/login/oauth2/code/facebook"
            scope:            - email
            - public_profile
          kakao:
            client-id: d4f7b42f2bc2fa71f32e46df52690d8f
            client-secret: cc91xPdskh27vUSOsQAEkowdV2KxOomv
            redirect-uri: "{baseUrl}/login/oauth2/code/kakao"
            scope:            - profile_nickname
            - account_email
            authorization-grant-type: authorization_code
            client-authentication-method: POST
          naver:
            client-id: CFSqjzsoiWCqb6yYar46
            client-secret: HmwivZYqm0
            redirect-uri: "{baseUrl}/login/oauth2/code/naver"
            authorization-grant-type: authorization_code
            scope:            - nickname
            - email
            - gender
            - age
            - profile_image
        provider:
          facebook:
            authorization-uri: https://www.facebook.com/v3.0/dialog/oauth
            token-uri: https://graph.facebook.com/v3.0/oauth/access_token
            user-info-uri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
      

    










